AllCops:
  SuggestExtensions: false
  NewCops: enable

  Exclude:
    - 'bin/*'
    
Style/Documentation:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/OneClassPerFile:
  Enabled: false
Naming/BlockForwarding:
  Enabled: false
Style/ArgumentsForwarding:
  Enabled: false
  
Metrics/AbcSize:
  Max: 100
Metrics/CyclomaticComplexity:
  Max: 100
Metrics/MethodLength:
  Max: 50
Metrics/BlockLength:
  Max: 100
Metrics/PerceivedComplexity:
  Max: 50
Layout/LineLength:
  Max: 140
